name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing to make this project better😎  Please keep up and follow to solve this issue.  Please feel free to draft a [pull request here](https://github.com/TermuxArch/TermuxArch/pulls) too to resolve this issue by tapping "new" at [this link](https://github.com/TermuxArch/TermuxArch/pulls).  Do not worry if it is not perfect on your first attempt.  This is what pull requests are for, in order to better understand and to improve the published source code.'
        pr-message: 'Thank you for contributing to make this project better🎉'
